#ifdef USE_BASIC
.decl CallGraphEdge(s:number, mi:MethodInvocation, t:number, ms:Method)
CallGraphEdge(0, mi, 0, ms) :-
  basic.ResolveInvocation(rv, mi, ms),
  basic.VirtualMethodInvocation_BaseType(mi, rv).
CallGraphEdge(0, mi, 0, ms) :-
  MethodInvocation_Method(mi, ms).
#endif

#ifdef USE_CALLGRAPH
.decl CallGraphEdge(callerCtx:symbol, mi:MethodInvocation, calleeCtx:symbol, ms:Method)
CallGraphEdge("", mi, "", ms) :-
  mainAnalysis.CallGraphEdge(_, mi, _, ms).
#endif
